2024-03-18 06:24:48 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}
2024-03-18 06:24:59 | WARNING    | epic_games.agent:get_order_history:467 | Failed to get order history, cookie may have expired - {}
2024-03-18 06:25:00 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'The Bridge', 'url': 'https://store.epicgames.com/en-US/p/the-bridge'}
2024-03-18 06:25:00 | DEBUG    | __main__:create_tasks:66 | Put task - {'title': 'Deus Ex - Mankind Divided', 'url': 'https://store.epicgames.com/en-US/p/deus-ex-mankind-divided-4c6370'}
2024-03-18 06:25:04 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/the-bridge'}
2024-03-18 06:25:09 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/deus-ex-mankind-divided-4c6370'}
2024-03-18 06:25:18 | INFO    | epic_games.agent:claim_weekly_games:326 | claim_weekly_games - {'action': 'move to webPurchaseContainer iframe'}
2024-03-18 06:25:20 | INFO    | epic_games.agent:claim_weekly_games:328 | claim_weekly_games - {'action': 'click payment button'}
2024-03-18 06:25:21 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0xc1 in position 0: invalid start byte - {}
Traceback (most recent call last):
  File "/home/runner/work/epic_/epic_/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py", line 145, in handler
    data = await response.json()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 614, in json
    return mapping.from_maybe_impl(await self._impl_obj.json())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_network.py", line 610, in json
    return json.loads(await self.text())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_network.py", line 607, in text
    return content.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc1 in position 0: invalid start byte
2024-03-18 06:25:55 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:25:55 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:25:57 | ERROR    | hcaptcha_challenger.agents.playwright.control:handler:153 | 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte - {}
Traceback (most recent call last):
  File "/home/runner/work/epic_/epic_/epic/src/claim.py", line 162, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/hcaptcha_challenger/agents/playwright/control.py", line 145, in handler
    data = await response.json()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 614, in json
    return mapping.from_maybe_impl(await self._impl_obj.json())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_network.py", line 610, in json
    return json.loads(await self.text())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_network.py", line 607, in text
    return content.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte
2024-03-18 06:26:27 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/the-bridge'}
2024-03-18 06:26:32 | INFO    | epic_games.agent:claim_weekly_games:294 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/deus-ex-mankind-divided-4c6370'}
2024-03-18 06:26:41 | INFO    | epic_games.agent:claim_weekly_games:326 | claim_weekly_games - {'action': 'move to webPurchaseContainer iframe'}
2024-03-18 06:26:43 | INFO    | epic_games.agent:claim_weekly_games:328 | claim_weekly_games - {'action': 'click payment button'}
2024-03-18 06:26:48 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:27:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:27:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:28:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:28:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:29:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:29:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:30:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:30:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:31:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:31:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:32:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:32:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:33:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:33:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
2024-03-18 06:34:49 | ERROR    | hcaptcha_challenger.agents.playwright.control:execute:615 | task interrupt <backcall> - {'reason': 'Failed to obtain challenge task'}
2024-03-18 06:34:49 | DEBUG    | epic_games.agent:insert_challenge:106 | task done - {'sattus': 'success'}
