{"text": "2024-03-25 06:26:29 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:01.912526", "seconds": 1.912526}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "stash", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3810, "name": "MainProcess"}, "thread": {"id": 140366733187968, "name": "MainThread"}, "time": {"repr": "2024-03-25 06:26:29.658103+08:00", "timestamp": 1711319189.658103}}}
{"text": "2024-03-25 06:26:36 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}\n", "record": {"elapsed": {"repr": "0:00:09.067890", "seconds": 9.06789}, "exception": null, "extra": {"task": "claim_epic_games"}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "claim_epic_games", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 97, "message": "Try to flush cookie", "module": "claim", "name": "__main__", "process": {"id": 3810, "name": "MainProcess"}, "thread": {"id": 140366733187968, "name": "MainThread"}, "time": {"repr": "2024-03-25 06:26:36.813467+08:00", "timestamp": 1711319196.813467}}}
{"text": "2024-03-25 06:26:36 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3810), thread 'MainThread' (140366733187968): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 98, in claim_epic_games\n    if await epic.authorize(page):\n  File \"/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py\", line 260, in authorize\n    match await self._login(page):\n  File \"/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py\", line 234, in _login\n    await page.goto(URL_CLAIM, wait_until=\"domcontentloaded\")\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 8612, in goto\n    await self._impl_obj.goto(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_page.py\", line 500, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 509, in wrap_api_call\n    return await cb()\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 97, in inner_send\n    result = next(iter(done)).result()\nplaywright._impl._errors.TargetClosedError: Target page, context or browser has been closed\n", "record": {"elapsed": {"repr": "0:00:09.076268", "seconds": 9.076268}, "exception": {"type": "TargetClosedError", "value": "Target page, context or browser has been closed", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "run", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (3810), thread 'MainThread' (140366733187968):", "module": "claim", "name": "__main__", "process": {"id": 3810, "name": "MainProcess"}, "thread": {"id": 140366733187968, "name": "MainThread"}, "time": {"repr": "2024-03-25 06:26:36.821845+08:00", "timestamp": 1711319196.821845}}}
