{"text": "2024-04-11 06:28:58 | INFO    | __main__:stash:131 | run - {'image': '20231121', 'version': '0.10.1.post2', 'role': 'EpicPlayer', 'headless': True}\n", "record": {"elapsed": {"repr": "0:00:02.119120", "seconds": 2.11912}, "exception": null, "extra": {"image": "20231121", "version": "0.10.1.post2", "role": "EpicPlayer", "headless": true}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "stash", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 131, "message": "run", "module": "claim", "name": "__main__", "process": {"id": 3885, "name": "MainProcess"}, "thread": {"id": 140205906635648, "name": "MainThread"}, "time": {"repr": "2024-04-11 06:28:58.710856+08:00", "timestamp": 1712788138.710856}}}
{"text": "2024-04-11 06:29:06 | INFO    | __main__:claim_epic_games:97 | Try to flush cookie - {'task': 'claim_epic_games'}\n", "record": {"elapsed": {"repr": "0:00:09.982146", "seconds": 9.982146}, "exception": null, "extra": {"task": "claim_epic_games"}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "claim_epic_games", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 97, "message": "Try to flush cookie", "module": "claim", "name": "__main__", "process": {"id": 3885, "name": "MainProcess"}, "thread": {"id": 140205906635648, "name": "MainThread"}, "time": {"repr": "2024-04-11 06:29:06.573882+08:00", "timestamp": 1712788146.573882}}}
{"text": "2024-04-11 06:29:10 | SUCCESS    | epic_games.agent:_login:253 | login - {'result': 'Successfully refreshed tokens'}\n", "record": {"elapsed": {"repr": "0:00:13.578931", "seconds": 13.578931}, "exception": null, "extra": {"result": "Successfully refreshed tokens"}, "file": {"name": "agent.py", "path": "/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py"}, "function": "_login", "level": {"icon": "✅", "name": "SUCCESS", "no": 25}, "line": 253, "message": "login", "module": "agent", "name": "epic_games.agent", "process": {"id": 3885, "name": "MainProcess"}, "thread": {"id": 140205906635648, "name": "MainThread"}, "time": {"repr": "2024-04-11 06:29:10.170667+08:00", "timestamp": 1712788150.170667}}}
{"text": "2024-04-11 06:29:42 | ERROR    | __main__:run:158 | An error has been caught in function 'run', process 'MainProcess' (3885), thread 'MainThread' (140205906635648): - {}\nTraceback (most recent call last):\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 162, in <module>\n    asyncio.run(run())\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/runners.py\", line 44, in run\n    return loop.run_until_complete(main)\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 636, in run_until_complete\n    self.run_forever()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n    self._run_once()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n    handle._run()\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/asyncio/events.py\", line 80, in _run\n    self._context.run(self._callback, *self._args)\n> File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 158, in run\n    await agent.stash()\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 151, in stash\n    await self.claim_epic_games(context)\n  File \"/home/runner/work/epic_/epic_/epic/src/claim.py\", line 99, in claim_epic_games\n    cookies = await epic.flush_token(context)\n  File \"/home/runner/work/epic_/epic_/epic/src/epic_games/agent.py\", line 273, in flush_token\n    await page.goto(\"https://www.epicgames.com/account/personal\", wait_until=\"networkidle\")\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py\", line 8638, in goto\n    await self._impl_obj.goto(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_page.py\", line 500, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 59, in send\n    return await self._connection.wrap_api_call(\n  File \"/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/playwright/_impl/_connection.py\", line 513, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nplaywright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://www.epicgames.com/account/personal\", waiting until \"networkidle\"\n\n", "record": {"elapsed": {"repr": "0:00:46.213432", "seconds": 46.213432}, "exception": {"type": "TimeoutError", "value": "Page.goto: Timeout 30000ms exceeded.\nCall log:\nnavigating to \"https://www.epicgames.com/account/personal\", waiting until \"networkidle\"\n", "traceback": true}, "extra": {}, "file": {"name": "claim.py", "path": "/home/runner/work/epic_/epic_/epic/src/claim.py"}, "function": "run", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 158, "message": "An error has been caught in function 'run', process 'MainProcess' (3885), thread 'MainThread' (140205906635648):", "module": "claim", "name": "__main__", "process": {"id": 3885, "name": "MainProcess"}, "thread": {"id": 140205906635648, "name": "MainThread"}, "time": {"repr": "2024-04-11 06:29:42.805168+08:00", "timestamp": 1712788182.805168}}}
